### ISSUE TITLE
run.py error

### ISSUE THREAD

**Issue by paresh795** [filip-michalsky/SalesGPT#89]
I am facing this issue, Followed all the steps for installation and got this :

" from langchain.llms.base import create_base_retry_decorator
ImportError: cannot import name 'create_base_retry_decorator' from 'langchain.llms.base'"

**Comment by ZuzooVn** [comment]
@paresh795 

To resolve the problem caused by the version difference in Langchain, you can fix the code by editing it as follows:

Replace the existing code with the following line:
`from langchain_core.language_models.llms import create_base_retry_decorator`
This modification will address the issue by importing the necessary module from Langchain's updated code structure.

**Comment by paresh795** [comment]
thank you
